#' Clean housing price per province data
#'
#' There are several issues with the data frame
#' read_housing_price_data provides. First the column labels are not
#' terribly great. Second, the periods column contains some sort of
#' code instead of a year. Lastly, the regions column contains all
#' the municipality codes from the Netherlands
#'
#' @param df a data frame generated by read_housing_price_data
#' @return a data frame with four columns: Gemeentenaam, Provincienaam, year and `housing price`.
#' @import stringr
#' @importFrom dplyr left_join
#' @importFrom rlang .data
#' @noRd

clean_housing_price_data_province <- function(df){
  df <- filter(df, .data$RegioS == "PV20  " | .data$RegioS == "PV22  " | .data$RegioS == "PV21  ")
  colnames(df)[which(colnames(df) == "Perioden")] <- "year"
  colnames(df)[which(colnames(df) == "GemiddeldeVerkoopprijs_1")] <- "Average selling price"
  colnames(df)[which(colnames(df) == "RegioS")] <- "Province"
  
  df[["year"]] <- as.integer(stringr::str_extract(df[["year"]], "^[0-9]{4}"))
  df
}
