#' Clean housing stock data
#'
#' There are several issues with the data frame
#' read_housing_stock_data provides. First the column labels are not
#' terribly great. Second, the periods column contains some sort of
#' code instead of a year. Lastly, the regions column is superfluous,
#' as there is only one region (the north of the Netherlands).
#'
#' @param df a data frame generated by read_housing_stock_data
#' @param codes_df a data frame generated by read_municipality
#' @return a data frame with four columns: Gemeentenaam, Provincienaam, year and `housing stock`.
#' @import stringr
#' @importFrom dplyr left_join
#' @importFrom rlang .data
#' @noRd

clean_housing_stock_data <- function(df,codes_df) {
  codes_df <- filter(codes_df, .data$Provincienaam == "Groningen" | .data$Provincienaam == "Drenthe" |
                       .data$Provincienaam == "Friesland")
  df <- dplyr::left_join(codes_df, df, by = c("GemeentecodeGM" = "Regions"))
  colnames(df)[which(colnames(df) == "Periods")] <- "year"
  colnames(df)[which(colnames(df) == "InitialStock_1")] <- "housing stock"
  colnames(df)[which(colnames(df) == "Gemeentenaam")] <- "municipality"
  colnames(df)[which(colnames(df) == "Provincienaam")] <- "province"
  df[["year"]] <- as.integer(stringr::str_extract(df[["year"]], "^[0-9]{4}"))
  df[["Gemeentecode"]] <- NULL
  df[["GemeentecodeGM"]] <- NULL
  df[["Provinciecode"]] <- NULL
  df[["ProvinciecodePV"]] <- NULL
  df
}

