#' Clean housing price per province data
#'
#' @param df a data frame generated by read_housing_price_data_province
#' @return a data frame with four columns: year, province and `average selling price`.
#' @import stringr
#' @importFrom rlang .data
#' @noRd

clean_housing_price_data_province <- function(df){
  df <- filter(df, .data$RegioS == "PV20  " | .data$RegioS == "PV22  " | .data$RegioS == "PV21  ")
  colnames(df)[which(colnames(df) == "Perioden")] <- "year"
  colnames(df)[which(colnames(df) == "GemiddeldeVerkoopprijs_1")] <- "Average selling price"
  colnames(df)[which(colnames(df) == "RegioS")] <- "Province"
  
  df[["year"]] <- as.integer(stringr::str_extract(df[["year"]], "^[0-9]{4}"))
  df
}
