#' Clean migration data from the imputed data
#'
#' There are several issues with the data frame register_imputed
#' data. First, we need to subset the dataframe, so that only the
#' necessary characteristics are taken, and then subset by selecting
#' only years 2015 and 2019. A new column depicting the balance of the
#' population is added for the necessary plots and the map
#' representation.
#'
#' @param imputed_data a data frame generated by get_data("register_imputed")
#' @return a data frame with five columns: municipality, province, 2015, 2019 and Balance.
#' @importFrom tidyr spread
#' @noRd
filter_imputed_migration_data <- function(imputed_data){
  df <- select(imputed_data, municip_code, municipality, province, year, population)
  df <- df[df$year == 2015 | df$year == 2019, ]
  
  df <- tidyr::spread(df, year, 'population')
  
  Balance <- c()
  endp <- c()
  startp <- c()
  for (i in 1:nrow(df)){
    endp <- as.numeric(df[[5]][i])
    startp <- as.numeric(df[[4]][i])
    Balance[i] <- endp - startp
  }
  df <- cbind(df, Balance)
}
