#' Read housing stock data
#'
#' This function retrieves housing stock counts for 2015-2019 of some
#' municipalities from provinces of Groningen and Drenthe
#' @importFrom utils read.csv
#' @noRd
read_housing_stock_data2 <- function() {
  data = utils::read.csv(
    file = "C:/Users/Augustin/Desktop/housingmarket_municip_Gr_DR.csv",
    head = TRUE,
    sep = ";")
}

#' Clean housing stock data
#'
#' There are several issues with the data frame
#' read_housing_stock_data provides. First the column labels are not
#' terribly great. Second, the periods column contains some sort of
#' code instead of a year. Lastly, the regions column is superfluous,
#' as there is only one region (the north of the Netherlands.
#'
#' @param df a data frame generated by read_housing_stock_data2
#' @return a data frame with three columns: municipality, year and `housing stock`.
#' @import stringr
#' @import dplyr
#' @noRd
clean_housing_stock_data2 <- function(df) {
  #Rename regions from their code to the name, some codes do not match to the general list they give
  levels(df[["Regions"]]) <- c("GM005-unknown","Delfzijl","GM0017-unknown",
                               "GM0022-unknown","Assen", "Emmen","Hoogeveen",
                               "Meppel","Tynaarlo","Het Hogeland")
  colnames(df)[which(colnames(df) == "Periods")] <- "year"
  colnames(df)[which(colnames(df) == "InitialStock_1")] <- "housing stock"
  df[["year"]] <- as.integer(stringr::str_extract(df[["year"]], "^[0-9]{4}"))
  #remove rows where the housing stock is not available at least in one year
  #What to do with municipalities that do not have records for every year shall be discussed
    df = df[!(is.na(df$`housing stock`)), ]
  #remove ID and Purpose columns
    df = dplyr::select(df, -ID, -Purpose)
  df
}
