#'Plot the general average selling price of houses
#'
#'This plot represents the average selling price of houses in the north of
#'the Netherlands
#'
#'@param df a data frame generated by clean_housing_price_data_province
#'@return a plot with the Average selling price in years 2015-2019
plot_north_housing_price <- function(df){

df_2015 <- filter(df, df$year == 2015)
df_2016 <- filter(df, df$year == 2016)
df_2017 <- filter(df, df$year == 2017)
df_2018 <- filter(df, df$year == 2018)
df_2019 <- filter(df, df$year == 2019)

data_north = data.frame(year = numeric(0), "Price" = numeric(0))
data_north[nrow(data_north)+1, ] <- c(2015, sum(df_2015$`Average selling price`)/3)
data_north[nrow(data_north)+1, ] <- c(2016, sum(df_2016$`Average selling price`)/3)
data_north[nrow(data_north)+1, ] <- c(2017, sum(df_2017$`Average selling price`)/3)
data_north[nrow(data_north)+1, ] <- c(2018, sum(df_2018$`Average selling price`)/3)
data_north[nrow(data_north)+1, ] <- c(2019, sum(df_2019$`Average selling price`)/3)


fig <- plotly::plot_ly(data_north, x = data_north$year, y = data_north$Price,
               type = 'scatter', mode = 'lines')
fig <- fig %>% layout(title = 'The average selling price of houses in the north of the Netherlands in 2015-2019',
                      xaxis = list(title = 'year'),
                      yaxis = list (title = 'Average selling price in euros'))
fig
}