#' Read housing stock data
#'
#' This function retrieves housing stock counts for 2015-2019 of the
#' north of the Netherlands.
#' @import jsonlite
#' @noRd
read_housing_stock_data <- function() {
  jsonlite::read_json(paste0(
    "https://opendata.cbs.nl/ODataApi/OData/81955ENG/TypedDataSet/",
    "?$filter=(substringof('LD01',Regions)) and ", # Filter statement
    "((Periods eq '2015JJ00') or ",
    "(Periods eq '2016JJ00') or ",
    "(Periods eq '2017JJ00') or ",
    "(Periods eq '2018JJ00') or ",
    "(Periods eq '2019JJ00')) and ",
    "(Purpose eq 'T001419')",
    "&$select=Periods,Regions,InitialStock_1"), # Column select
    simplifyDataFrame = TRUE)
}

#' Clean housing stock data
#'
#' There are several issues with the data frame
#' read_housing_stock_data provides. First the column labels are not
#' terribly great. Second, the periods column contains some sort of
#' code instead of a year. Lastly, the regions column is superfluous,
#' as there is only one region (the north of the Netherlands.
#'
#' @param df a data frame generated by read_housing_stock_data
#' @return a data frame with two columns: year and `housing stock`.
#' @import stringr
#' @noRd
clean_housing_stock_data <- function(df) {
  df[["Regions"]] <- NULL
  colnames(df)[which(colnames(df) == "Periods")] <- "year"
  colnames(df)[which(colnames(df) == "InitialStock_1")] <- `housing stock`
  df[["year"]] <- as.integer(stringr::str_extract(df[["year"]], "^[0-9]{4}"))
  df
}
