#' Subset the migration data from the imputed data for the province of Groningen
#'
#' 3 separate datasets with the migration data are required for the barplots
#' of the migration indicator for each province
#'
#' @param migr_data a data frame generated by get_data("register_imputed")
#' @return a data frame with five columns: municipality, province, 2015, 2019 and Balance.
#' @importFrom tidyr spread
#' @noRd
subset_GR_migration_data <- function(df){
  df_GR <- df[df$province == "Groningen", ]
}
  